#!/bin/bash
if [ $1 ]; then
	echo "Spreading changes from revision $1 ..."
	OUT=`git diff --name-status $1 | sed -n 's/^M\t//p'`
else
	echo "Spreading changes from actual status..."
	OUT=`git status --porcelain | sed -n 's/^\(\ M\ \|A\ \ \)//p'`
fi

for file in $OUT
do
	echo -n "Copy $file ... "
	cp $file /home/polly/git-root/BGS/gospeed/$file
	if [ $? -eq 0 ]; then
		echo -e "[\e[00;32mOK\e[00m]";
	else
		echo -e "[\e[00;31mError\e[00m]";
	fi
done

echo "Done"


#redis-server > /dev/null &
#redis_pid=$!
#echo "Redis PID: $redis_pid"
#juggernaut > /dev/null &
#juggernaut_pid=$!
#echo "Juggernaut PID: $juggernaut_pid"
#ruby scripts/jugger.rb > /dev/null &
#jugger_pid=$!
#echo "Ruby jugger PID: $jugger_pid"
##unicorn -c .tele/unicorn_config.rb
#rackup
#
#echo "Killing child processes..."
#trap "kill $redis_pid" INT TERM EXIT
#trap "kill $juggernaut_pid" INT TERM EXIT
#trap "kill $jugger_pid" INT TERM EXIT
